[package]
name = "reminder_rs"
version = "0.1.0"
authors = ["jellywx <judesouthworth@pm.me>"]
edition = "2018"

[dependencies]
serenity = {git = "https://github.com/acdenisSK/serenity", branch = "await_next"}
dotenv = "0.15"
tokio = {version = "0.2.19", features = ["fs", "sync", "process", "io-util"]}
reqwest = "0.10.6"
sqlx = {version = "0.3.5", default-features = false, features = ["runtime-tokio", "macros", "mysql", "bigdecimal", "chrono"]}
regex = "1.3.9"
async-trait = "0.1.36"
log = "0.4.11"
chrono = "0.4"
chrono-tz = "0.5"

[dependencies.regex_command_attr]
path = "./regex_command_attr"
